
model:
  # name: "Qwen/Qwen2-1.5B-Instruct" 
  name: "/home/xrrfolder/models/Qwen2.5-3B-Instruct" 
  max_seq_length: 1024

lora:
  r: 8
  alpha: 16                   # lora_alpha: LoRA Alpha
  bias: "none"                # bias
  task_type: "CAUSAL_LM"      # task_type

training:
  learning_rate: 1.0e-5       # learning_rate
  batch_size: 2
  gradient_accumulation_steps: 4 
  num_epochs: 3               # num_train_epochs
  max_grad_norm: 1.0
  warmup_ratio: 0.05
  lr_scheduler_type: "cosine"
  bf16: true

system:
  output_dir: "/home/xrrfolder/CELPO/outputs/sft" # output_dir
  save_steps: 50
  logging_steps: 10
  report_to: "none"
